export const menu = [
  {
    id: "administration",
    title: "administration",
    translate: "navigations.administration",
    type: "collapsible",
    role: ["admin"],
    icon: "settings",
    children: [
      {
        id: "allPredators",
        title: "allPredators",
        translate: "navigations.appConfig",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/app-config",
      },
      {
        id: "allUsers",
        title: "allUsers",
        translate: "navigations.allUsers",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-users",
      },
      {
        id: "allCountries",
        title: "allCountries",
        translate: "navigations.allCountries",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-countries",
      },
      {
        id: "allProvinces",
        title: "allProvinces",
        translate: "navigations.allProvinces",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-provinces",
      },
      {
        id: "allDistricts",
        title: "allDistricts",
        translate: "navigations.allDistricts",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-districts",
      },
      {
        id: "allCities",
        title: "allCities",
        translate: "navigations.allCities",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-cities",
      },
    ],
  },
  {
    id: "all-fsd-organs",
    title: "allFsdOrgans",
    translate: "navigations.allFsdOrgans",
    type: "item",
    icon: "users",
    url: "dashboard/admin/all-fsd-organs",
    users: ["admin"],
  },
  {
    id: "allFishDistricts",
    title: "allFishDistricts",
    translate: "navigations.allFishDistricts",
    type: "item",
    icon: "settings",
    url: "dashboard/superadmin/all-fish-districts",
    users: ["superadmin"],
  },
  {
    id: "predators",
    title: "predators",
    translate: "navigations.predators",
    type: "collapsible",
    role: ["superadmin"],
    icon: "settings",
    children: [
      {
        id: "allPredators",
        title: "allPredators",
        translate: "navigations.allPredators",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-predators",
      },
      {
        id: "allActivities",
        title: "allActivities",
        translate: "navigations.allActivities",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-activities",
      },
      {
        id: "allWaters",
        title: "allWaters",
        translate: "navigations.allWaters",
        type: "item",
        role: ["superadmin"],
        icon: "circle",
        url: "dashboard/superadmin/all-waters",
      },
    ],
  },
];
