export const menu = [
  {
    id: "administration",
    title: "administration",
    translate: "navigations.administration",
    type: "collapsible",
    users: ["superadmin"],
    icon: "settings",
    children: [
      {
        id: "allPredators",
        title: "allPredators",
        translate: "navigations.appConfig",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/app-config",
      },
      {
        id: "allUsers",
        title: "allUsers",
        translate: "navigations.allUsers",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-users",
      },
      {
        id: "allCountries",
        title: "allCountries",
        translate: "navigations.allCountries",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-countries",
      },
      {
        id: "allProvinces",
        title: "allProvinces",
        translate: "navigations.allProvinces",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-provinces",
      },
      {
        id: "allDistricts",
        title: "allDistricts",
        translate: "navigations.allDistricts",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-districts",
      },
      {
        id: "allCities",
        title: "allCities",
        translate: "navigations.allCities",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-cities",
      },
      {
        id: "allCities",
        title: "allCities",
        translate: "navigations.allAdmins",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-admins",
      },
      {
        id: "allAreas",
        title: "allAreas",
        translate: "navigations.allAreas",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-areas",
      },
    ],
  },
  {
    id: "allFishDistricts",
    title: "allFishDistricts",
    translate: "navigations.allFishDistricts",
    type: "item",
    icon: "settings",
    url: "dashboard/superadmin/all-fish-districts",
    users: ["superadmin"],
  },
  {
    id: "predators",
    title: "predators",
    translate: "navigations.predators",
    type: "collapsible",
    users: ["superadmin"],
    icon: "settings",
    children: [
      {
        id: "allPredators",
        title: "allPredators",
        translate: "navigations.allPredators",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-predators",
      },
      {
        id: "allActivities",
        title: "allActivities",
        translate: "navigations.allActivities",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-activities",
      },
      {
        id: "allWaters",
        title: "allWaters",
        translate: "navigations.allWaters",
        type: "item",
        icon: "circle",
        url: "dashboard/superadmin/all-waters",
      },
    ],
  },
  {
    id: "allUsers",
    title: "allUsers",
    translate: "navigations.myUsers",
    type: "item",
    icon: "users",
    url: "dashboard/admin/my-users",
    users: ["admin", "superadminArea"],
  },
  {
    id: "predators",
    title: "predators",
    translate: "navigations.predators",
    type: "item",
    icon: "users",
    url: "dashboard/admin/predators",
    users: ["admin", "superadminArea"],
  },
  {
    id: "predators",
    title: "predators",
    translate: "navigations.predatorRequests",
    type: "item",
    icon: "users",
    url: "dashboard/admin/all-observation-reports",
    users: ["admin", "superadminArea"],
  },
  {
    id: "allFishDistricts",
    title: "allFishDistricts",
    translate: "navigations.allFishDistricts",
    type: "item",
    icon: "settings",
    url: "dashboard/admin/all-fish-districts",
    users: ["admin", "superadminArea"],
  },
  {
    id: "adminSettings",
    title: "adminSettings",
    translate: "navigations.areaSettings",
    type: "item",
    icon: "settings",
    url: "dashboard/admin/area-settings",
    users: ["superadminArea"],
  },
  {
    id: "myAdmins",
    title: "myAdmins",
    translate: "navigations.myAdmins",
    type: "item",
    icon: "circle",
    url: "dashboard/admin/my-admins",
    users: ["superadminArea"],
  },
];
